#! /bin/sh

# Create the "configure" shell script from other files - principally
# "configure.ac", but also various m4 macro definitions.  Should be
# run in the top-level directory for a pqR source distribution if 
# "configure.ac" has been changed, or if "configure" is not present.

cat m4/R.m4 m4/bigendian.m4 m4/cairo.m4 m4/clibs.m4 \
    m4/codeset.m4 m4/gettext.m4 m4/gettext-lib.m4 \
    m4/java.m4 m4/libtool.m4 m4/ltoptions.m4 m4/ltversion.m4 \
    m4/ltsugar.m4 m4/lt~obsolete.m4 m4/stat-time.m4 > acinclude.m4
aclocal --output=aclocal.m4 -I .
autoconf -B .
rm aclocal.m4
rm acinclude.m4
rm -r autom4te.cache
