#!/bin/bash
#
# MATPROD - A LIBRARY FOR MATRIX MULTIPLICATION WITH OPTIONAL PIPELINING
#           Shell File to Run a Series of Tests
#
# Copyright (c) 2013 Radford M. Neal.
# 
#   The matprod library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

n=$1
k=$2
m=$3

while [ x$4 != x ]; do
  export $4
  shift
done

matprod-test 1 $n $k $m >/tmp/x$$

for prog in matprod-test piped-matprod-test; do
  echo $prog A; $prog 1 $n $k $m | cmp - /tmp/x$$
  echo $prog B; $prog 1 t $n $k $m | cmp - /tmp/x$$
  echo $prog C; $prog 1 $n $k $m t | cmp - /tmp/x$$
  if [ $n == $m ]; then
    echo $prog D; $prog 1 T $n $k $m | cmp - /tmp/x$$
    echo $prog E; $prog 1 $n $k $m T | cmp - /tmp/x$$
  fi
done
