#!/bin/bash

# Plot comparison of times for vec_mat and mat_vec.

(echo 0.Color: rgb:a/0/0;
 echo 1.Color: rgb:0/9/0;
 echo 2.Color: rgb:0/0/a;
 echo 3.Color: rgb:9/8/0;
 echo 4.Color: rgb:0/7/7;
 echo 5.Color: rgb:8/0/8;
 echo 6.Color: rgb:b/5/5;
 echo 7.Color: rgb:3/6/2;
 ( sed < $1.tim -e "1,/VEC_MAT/d" -e "/MAT_VEC/,\$d" \
    | sed "s/m/*60+/g" | R --vanilla --slave | grep -n .
   echo " "
   sed < $1.tim -e "1,/MAT_VEC/d" -e "/OUTER/,\$d" \
    | sed "s/m/*60+/g" | R --vanilla --slave | grep -n .
 ) 
) | sed "s/:\[1\]//" | xgraph -zw 0 -gw 1 -lf fixed -tf fixed -P -lny =900x450
