#!/bin/bash
#
# MATPROD - A LIBRARY FOR MATRIX MULTIPLICATION
#           Shell File to Run a Series of Tests (for outer)
#
# Copyright (c) 2013, 2017, 2018 Radford M. Neal.
# 
#   The matprod library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


# run-tests program
#
# Uses the given test program for a variety of tests, displaying timing
# information, along with some headers.


prog=$1-test

echo " "; echo OUTER

echo " "; time $prog 500000$Z 2 v 2789
echo " "; time $prog 500000$Z 3 v 2000
echo " "; time $prog 500000$Z 4 v 1555
echo " "; time $prog 2000000$Z 300 v 3
echo " "; time $prog 2000000$Z 23 v 34
echo " "; time $prog 20000$Z 230 v 341
echo " "; time $prog 100$Z 2231 v 3201
echo " "; time $prog 200$Z 7031 v 320
