#!/bin/bash
#
# MATPROD - A LIBRARY FOR MATRIX MULTIPLICATION
#           Shell File to Run Checks of One Multiplication
#
# Copyright (c) 2018 Radford M. Neal.
# 
#   The matprod library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


prog=$1-test

lower=$2
upper=$3

export CHECK=T

for n in `seq $lower $upper`; do
  for k in `seq $lower $upper`; do
    for m in `seq $lower $upper`; do
      echo -- $n $k $m --
      $prog 2 $n $k $m
      $prog 2 t $n $k $m
      $prog 2 $n t $k $m
      $prog 2 t $n t $k $m
    done
    echo -- symmetric $n $k $n --
    $prog 2 T $n $k $n
    $prog 2 $n T $k $n
  done
done
