#!/bin/bash
#
# MATPROD - A LIBRARY FOR MATRIX MULTIPLICATION
#           Shell File to Run a Series of Tests (for vec_vec)
#
# Copyright (c) 2013, 2017, 2018 Radford M. Neal.
# 
#   The matprod library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


prog=$1-test

echo " "; echo VEC_VEC

echo " "; time $prog 30000000$Z v 23 v
echo " "; time $prog 500000$Z v  901 v
echo " "; time $prog 50000$Z v 12345 v
echo " "; time $prog 5000$Z v 123456 v
echo " "; time $prog 500$Z v 1234567 v
