#!/bin/bash

# tim prefix ...
#
# Creates prefix.tim from prefix.out by extracting elapased time information,
# plus headers.

for i in $@; do
  j=`echo $i | sed s/\\.out//`
  grep "^[a-zA-Z]" $j.out | fgrep -v "user" | fgrep -v "sys"| fgrep -v "Check" \
    | sed "s/real *//" | sed "s/0m//" | sed "s/s//" >$j.tim
done
