#-*- Makefile -*-
include ../../gnuwin32/MkRules

DEFS=-DHAVE_CONFIG_H

CPPFLAGS=-I../../include -I. $(DEFS)

## done this way for parallel make
all:
	$(MAKE) -f Makefile.win makeMakedeps
	$(MAKE) -f Makefile.win libmatprod.a

CSOURCES = matprod.c

OBJS = $(CSOURCES:.c=.o)
libmatprod.a: $(OBJS)

clean:
	@$(RM) *.o *~ *.d Makedeps

distclean: clean
	@$(RM) libmatprod.a

# Dependencies
DEPS=$(CSOURCES:.c=.d)

makeMakedeps: $(DEPS)
	@$(RM) Makedeps
	@cat $(DEPS) >> Makedeps

-include Makedeps
